### ISSUE TITLE
Bug #4 in setSelectionAnchors

### ISSUE THREAD

**Issue by UlixDev** [pozyxLabs/Pozyx-Python-library#8] opened 2016-11-09 13:43 UTC
When I execute the snippet of code
    mode = SingleRegister(POZYX_ANCHOR_SEL_MANUAL)
    n = SingleRegister(how_many)
    tag.tag.setSelectionOfAnchors(mode, n)

The following traceback pops out

Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/home/osboxes/prj/dfw/Pozyx_scripts/meanTAGPositioning.py", line 25, in TAGInit
    tag.tag.setSelectionOfAnchors(mode, n)
  File "/usr/local/lib/python3.5/dist-packages/pypozyx/lib.py", line 1172, in setSelectionOfAnchors
    **assert nr_anchors[0] > 2 and nr_anchors[
TypeError: unorderable types: SingleRegister() > int()**

This bug appears only in python3.5

**Comment by laurentva** [comment] 2016-11-15 17:52
Couldn't reproduce the issue but didn't it appear only in Python2 instead of 3? It's directly related to Issue #9 but there were other things wrong in this function too so thanks, should be fixed now.

**Closed as completed by laurentva** 2016-11-15 17:52 UTC
